---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{ source_url }}?rev={{ revision }}'
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: psfedora01rm-app-0
    appstudio.openshift.io/component: psfedora01rm-app-0-comp-0
    pipelines.appstudio.openshift.io/type: build
  name: psfedora01rm-app-0-comp-0-on-pull-request
  namespace: konflux-perfscale-3-tenant
spec:
  params:
    - name: package-name
      value: libecpg
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: ociStorage
      value: "quay.io/konflux-fedora/$(context.taskRun.namespace)/psfedora01rm-app-0-comp-0:on-pr-{{revision}}"
    - name: build-platforms
      value:
        - localhost
        - linux/amd64
        - linux/arm64
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: strictArch
      value: "false"
    - name: self-ref-url
      value: "https://gitlab.com/fedora/infrastructure/konflux/rpmbuild-pipeline"
    - name: self-ref-revision
      value: c8a0bf7f6605239e7e2b3d8832c2627421ce0703
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://gitlab.com/fedora/infrastructure/konflux/rpmbuild-pipeline
      - name: revision
        value: c8a0bf7f6605239e7e2b3d8832c2627421ce0703
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-psfedora01rm-app-0-comp-0
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
